"""error_code_field_for_charge_points

Revision ID: 0005
Revises: 0004
Create Date: 2024-03-27 08:45:58.929031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge_points', sa.Column('error_code', sa.String(), nullable=True))
    op.drop_index('ix_network_name', table_name='networks')
    op.drop_index('ix_users_email', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_network_name', 'networks', ['name'], unique=False)
    op.drop_column('charge_points', 'error_code')
    # ### end Alembic commands ###
