"""separate_connections_table

Revision ID: 0009
Revises: 0008
Create Date: 2024-12-03 16:48:28.286133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('charge_point_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['charge_point_id'], ['charge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=True)
    op.create_index(op.f('ix_connections_status'), 'connections', ['status'], unique=False)
    op.drop_index('ix_charge_points_status', table_name='charge_points')
    op.drop_column('charge_points', 'ocpp_version')
    op.drop_column('charge_points', 'status')
    op.drop_column('charge_points', 'error_code')
    op.drop_constraint('ix_unique_configuration', 'configurations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ix_unique_configuration', 'configurations', ['id', 'charge_point_id'])
    op.add_column('charge_points', sa.Column('error_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('charge_points', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('charge_points', sa.Column('ocpp_version', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_charge_points_status', 'charge_points', ['status'], unique=False)
    op.drop_index(op.f('ix_connections_status'), table_name='connections')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_table('connections')
    # ### end Alembic commands ###
