"""evse_id_as_a_connectors_field

Revision ID: 0010
Revises: 0009
Create Date: 2024-04-28 17:22:34.834079

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charge_points', 'evse_id')
    op.add_column('connectors', sa.Column('evse_id', sa.Integer(), nullable=True))
    op.execute("ALTER TABLE connectors DROP CONSTRAINT connectors_pkey;")
    op.execute("CREATE UNIQUE INDEX connectors_pkey ON connectors (id, charge_point_id, evse_id);")
    op.execute("ALTER TABLE connectors ADD PRIMARY KEY USING INDEX connectors_pkey;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE connectors DROP CONSTRAINT connectors_pkey;")
    op.execute("CREATE UNIQUE INDEX connectors_pkey ON connectors (id, charge_point_id);")
    op.execute("ALTER TABLE connectors ADD PRIMARY KEY USING INDEX connectors_pkey;")
    op.drop_column('connectors', 'evse_id')
    op.add_column('charge_points', sa.Column('evse_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
