"""station_configurations_table

Revision ID: 0009
Revises: 0008
Create Date: 2024-04-26 15:58:36.346713

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
                    sa.Column('key', sa.String(), nullable=False),
                    sa.Column('value', sa.String(), nullable=False),
                    sa.Column('charge_point_id', sa.String(), nullable=False),
                    sa.Column('id', sa.String(length=20), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['charge_point_id'], ['charge_points.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('key', 'charge_point_id')
                    )
    op.create_index(op.f('ix_configurations_id'), 'configurations', ['id'], unique=True)
    op.create_unique_constraint('ix_unique_configuration', 'configurations', ['id', 'charge_point_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ix_unique_configuration', 'configurations', type_='unique')
    op.drop_index(op.f('ix_configurations_id'), table_name='configurations')
    op.drop_table('configurations')
    # ### end Alembic commands ###
