"""nullable_connection_status

Revision ID: 0010
Revises: 0009
Create Date: 2024-12-03 19:49:00.696623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connections', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_connections_status', table_name='connections')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_connections_status', 'connections', ['status'], unique=False)
    op.alter_column('connections', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
