"""modems_table_adjusted_tables

Revision ID: 0015
Revises: 0014
Create Date: 2024-12-06 12:25:37.468674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0015'
down_revision = '0014'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modems',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('iccid', sa.String(), nullable=True),
    sa.Column('imsi', sa.String(), nullable=True),
    sa.Column('charge_point_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['charge_point_id'], ['charge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('configurations', sa.Column('verbose', sa.String(), nullable=True))
    op.drop_index('ix_connectors_status', table_name='connectors')
    op.drop_column('connectors', 'reason')
    op.drop_column('connectors', 'custom_data')
    op.drop_column('connectors', 'status')
    op.drop_column('evses', 'custom_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evses', sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('connectors', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('connectors', sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('connectors', sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_connectors_status', 'connectors', ['status'], unique=False)
    op.drop_column('configurations', 'verbose')
    op.drop_table('modems')
    # ### end Alembic commands ###
