"""fixed_primary_keys

Revision ID: 0017
Revises: 0016
Create Date: 2024-12-07 17:21:16.927551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0017'
down_revision = '0016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'connectors', ['id', 'evse_id'])
    op.create_unique_constraint(None, 'evses', ['id', 'charge_point_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evses', type_='unique')
    op.drop_constraint(None, 'connectors', type_='unique')
    # ### end Alembic commands ###
