"""nullable_model_and_vendorname_fields

Revision ID: 0018
Revises: 0017
Create Date: 2024-12-09 13:01:51.930517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0018'
down_revision = '0017'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charge_points', 'vendor_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('charge_points', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charge_points', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('charge_points', 'vendor_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
