"""removed_networks_and_modems_tables

Revision ID: 0020
Revises: 0019
Create Date: 2024-12-10 08:18:43.386190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0020'
down_revision = '0019'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modems')
    op.alter_column('connections', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('connections_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connections', 'id',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('connections_id_seq'::regclass)"))
    op.create_table('modems',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('modems_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('iccid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('imsi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('charge_point_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['charge_point_id'], ['charge_points.id'], name='modems_charge_point_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='modems_pkey')
    )
    # ### end Alembic commands ###
