"""removed_configurations_table

Revision ID: 0021
Revises: 0020
Create Date: 2024-12-10 08:22:06.437399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0021'
down_revision = '0020'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configurations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('charge_point_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('verbose', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['charge_point_id'], ['charge_points.id'], name='configurations_charge_point_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='configurations_pkey'),
    sa.UniqueConstraint('key', 'charge_point_id', name='configurations_key_charge_point_id_key')
    )
    # ### end Alembic commands ###
