"""adjusted_grids_table

Revision ID: 0022
Revises: 0021
Create Date: 2024-12-10 08:31:02.904383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0022'
down_revision = '0021'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grids', 'capacity',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('grids_name_key', 'grids', type_='unique')
    op.create_unique_constraint(None, 'grids', ['account_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grids', type_='unique')
    op.create_unique_constraint('grids_name_key', 'grids', ['name'])
    op.alter_column('grids', 'capacity',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
